# Generated by Django 2.0.6 on 2019-01-04 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='COURSE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=6)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name_plural': 'courses',
            },
        ),
        migrations.CreateModel(
            name='FILE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.CharField(max_length=40)),
                ('file_name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name_plural': 'files',
            },
        ),
        migrations.CreateModel(
            name='PAPER',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_type', models.CharField(choices=[('m', 'Mid Semester'), ('e', 'End Semester'), ('q', 'Quiz')], max_length=1)),
                ('paper_year', models.CharField(max_length=4)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploadfile.COURSE')),
            ],
            options={
                'verbose_name_plural': 'papers',
            },
        ),
        migrations.CreateModel(
            name='PAPER_UPLOAD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploadfile.PAPER')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'paper uploads',
            },
        ),
        migrations.AddField(
            model_name='file',
            name='paper_upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploadfile.PAPER_UPLOAD'),
        ),
    ]
